### ISSUE TITLE
Add ZSH completion code for Crystal compiler and shards command

### ISSUE THREAD

**Issue by joshuamzm** [veelenga/crystal-zsh#3]
It should be great to have auto completion for crystal and shards commands. Any thoughts about it?

**Comment by veelenga** [comment]
ZSH completion is delivered by crystal team actually. Take a look [here](https://github.com/crystal-lang/crystal/blob/master/etc/completion.zsh). It was not updated for a while, but at least it works for me locally (oh my zsh on OS X):

![crystal-zsh-completion](https://cloud.githubusercontent.com/assets/3624712/24931907/ce9b611a-1f17-11e7-9152-5c1dc00a2033.gif)

I will prepare a new pull request to add missing stuff to the file in crystal repo...

Well, this autocompletion does not work together with aliases defined in [crystal.plugin.zsh](https://github.com/veelenga/crystal-zsh/blob/master/crystal.plugin.zsh#L11-L27)... So you can't do `cr --<TAB>` for now. But that is possible to achieve it with `compdef`:

```sh
$ compdef cr=crystal
$ cr --<TAB>
--help     -- show help
--version  -- show version
```

I think we can adjust crystal-zsh, so it will work nicely together with official crystal completion...
